# This is a basic workflow to help you get started with Actions

name: Deploy NGINX Configuration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Download NGINX configuration from S3
        run: |
          aws s3 cp s3://hybbuck2/nginx.conf .
      
      - name: Transfer NGINX configuration to EC2 Instance 1
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@13.232.225.115 "scp nginx.conf /etc/nginx/nginx.conf"

      - name: Transfer NGINX configuration to EC2 Instance 2
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@35.154.221.192 "scp nginx.conf /etc/nginx/nginx.conf"
